### ISSUE TITLE
ImportError when import binarize_labeled_data

### ISSUE THREAD

**Issue by liybu36** [zhangruinan/SmoothNLP#1]
I get ImportError when trying to load binarize_labeled_data in smoothnlp.treebanks
![image](https://user-images.githubusercontent.com/8764562/52785983-8075af00-3094-11e9-82f4-fbbbac70b3d9.png)

**Comment by zhangruinan** [comment]
sorry, this problem should be fixed by now. The README was ahead of the module codes.
